os: linux
dist: bionic

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -vb tests/

after_success:
  - coverage report -m
  - bash <(curl -s https://codecov.io/bash)

deploy:
  edge: true
  provider: pypi
  username: meyer1994
  skip_existing: true
  on:
    tags: true
