os: linux
dist: bionic

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements-dev.txt

script:
  - coverage run -m unittest discover -vb tests/

after_success:
  - coverage report -m
  - bash <(curl -s https://codecov.io/bash)
